version: 2.1

jobs:
  build:
    docker:
      - image: circleci/python:3.8
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.7
          docker_layer_caching: true
      - run:
          name: Build Docker Image
          command: docker build -t $DOCKERHUB_USERNAME/my-python-app:${CIRCLE_SHA1} .
      - run:
          name: Docker Login
          command: echo $DOCKERHUB_PASSWORD | docker login -u $DOCKERHUB_USERNAME --password-stdin
      - run:
          name: Push Docker Image
          command: docker push $DOCKERHUB_USERNAME/my-python-app:${CIRCLE_SHA1}
      - run:
          name: Install dependencies
          command: |
            python -m venv venv
            . venv/bin/activate
            pip install --no-cache-dir -r requirements.txt
      - run:
          name: Run tests
          command: |
            . venv/bin/activate
            python -m unittest discover -s tests -p "unittest_*.py"

workflows:
  version: 2
  build-and-test:
    jobs:
      - build