version: 2.1

jobs:
  test:
    docker:
      - image: cimg/python:3.8
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            python -m venv venv
            . venv/bin/activate
            pip install --upgrade pip
            pip install -r requirements.txt --verbose
      - run:
          name: Set PYTHONPATH
          command: |
            echo "export PYTHONPATH=$(pwd):$(pwd)/airView" >> $BASH_ENV
      - run:
          name: Run tests
          command: |
            . venv/bin/activate
            python -m unittest discover -s tests -p "unittest_*.py"
      - store_test_results:
          path: test-results

  build_and_push:
    docker:
      - image: cimg/python:3.8
    steps:
      - checkout
      - setup_remote_docker:
          version: 23.0.0  # Update to a newer supported version
      - run:
          name: Build Docker Image
          command: |
            docker build -t $DOCKERHUB_USERNAME/my-python-app:${CIRCLE_SHA1} .
      - run:
          name: Authenticate with Docker Hub
          command: |
            echo "$DOCKERHUB_PASS" | docker login --username $DOCKERHUB_USERNAME --password-stdin
      - run:
          name: Push Docker Image to Docker Hub
          command: |
            docker push $DOCKERHUB_USERNAME/my-python-app:${CIRCLE_SHA1}

workflows:
  version: 2
  test_and_deploy:
    jobs:
      - test
      - build_and_push:
          requires:
            - test
          filters:
            branches:
              only: main