version: 2.1

jobs:
  build:
    docker:
      - image: circleci/python:3.8
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            python -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt
      - run:
          name: Run tests
          command: |
            . venv/bin/activate
            python -m unittest discover -s tests -p "unittest_*.py"
      - setup_remote_docker:
          version: 20.10.7
      - run:
          name: Build and Push Docker Image
          command: |
            if [ -z "$DOCKERHUB_USERNAME" ] || [ -z "$CIRCLE_SHA1" ]; then
              echo "Environment variables DOCKERHUB_USERNAME and/or CIRCLE_SHA1 are not set"
              exit 1
            fi
            docker login -u "$DOCKERHUB_USERNAME" -p "$DOCKERHUB_PASSWORD"
            docker build -t "$DOCKERHUB_USERNAME/my-python-app:${CIRCLE_SHA1}" .
            docker push "$DOCKERHUB_USERNAME/my-python-app:${CIRCLE_SHA1}"

workflows:
  version: 2
  build_and_test:
    jobs:
      - build